services:
  awbl-db:
    image: postgres:alpine
    container_name: awbl-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  awbl-redis:
    image: redis:7-alpine
    container_name: awbl-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      
  awbl-redis-ui:
    image: redis/redisinsight:latest
    container_name: awbl-redis-ui
    restart: always
    ports:
      - '5540:5540'

  awbl-app:
    build:
      context: .
    container_name: awbl-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@awbl-db:5432/postgres
      - REDIS_HOST=awbl-redis
      - REDIS_PORT=6379
    depends_on:
      - awbl-db
      - awbl-redis
volumes:
  db-data:
  redis-data:
  